= EDF

:toc:

// NOTE: line below is if github ever bakes in support for AsciiDoc includes
// include::docs/modules/ROOT/pages/index.adoc[tag=EDF_Home]

== Description
Embedded Development Framework (EDF) is a collection of libraries intended for use in embedded systems. It consists of the core library of platform independent building blocks, peripheral interfaces, drivers for specific ICs and common circuits.

// == Installation

// [source,bash]
// -----
// $ git clone https://github.com/AdamVeazey/edf.git
// $ cd yourlibrary
// $ mkdir build
// $ cd build
// $ cmake ..
// $ cd ..
// $ cmake --build build/
// -----

// === Using CMake

// Add the following to your `CMakeLists.txt`:

// [source,cmake]
// ----
// find_package(MyAwesomeLibrary REQUIRED)
// target_link_libraries(your_target MyAwesomeLibrary)
// ----

== Documentation

For detailed information on the API and usage, please refer to the online link:https://AdamVeazey.github.io/edf/docs/main/index.html[documentation].

== License

EDF is distributed under the BSD-3-Clause License. See the `LICENSE` file for details.

// == Versioning

// EDF follows Semantic Versioning. For a list of released versions, see the link:https://github.com/AdamVeazey/edf/tags[tags on this repository].

== Examples

Check out the `examples` directory for practical use cases and code snippets.