= Color

include::ROOT:partial$refs.adoc[]

== Overview
Color is a 32-bit value where 8-bits are dedicated to red, green, blue, and alpha. Color565 is a 16-bit value where 5 bits are dedicated to red, 6 for blue, and 5 for blue. Pre-defined named colors are static members of Color.

== Initialization

=== Color(), Color565()
[source,indent=0,c++]
----
include::{path_example_edf_color_main_cpp}[tag=init_default]
include::{path_example_edf_color_main_cpp}[tag=init_default_565]
----

---

=== Color( initialValue ), Color565( initialValue )
[source,indent=0,c++]
----
include::{path_example_edf_color_main_cpp}[tag=init_initial_value]
include::{path_example_edf_color_main_cpp}[tag=init_initial_value_565]
----

---

=== Color( r, g, b, a )
`a` is optional, default's to 255 if not provided which means opacity is 100%.

[source,indent=0,c++]
----
include::{path_example_edf_color_main_cpp}[tag=init_rgba]
----

---

=== Color565( r, g, b )
[source,indent=0,c++]
----
include::{path_example_edf_color_main_cpp}[tag=init_rgba_565]
----

---

=== Color565( c )
`c` is a `Color`

[source,indent=0,c++]
----
include::{path_example_edf_color_main_cpp}[tag=init_color_565]
----

== Set Color Components

=== setR( r ), setG( g ), setB( b ), setA( a )

NOTE: `setA( a )` only exists for `Color` not `Color565`.

[source,indent=0,c++]
----
include::{path_example_edf_color_main_cpp}[tag=init_default]
include::{path_example_edf_color_main_cpp}[tag=set_rgba]

include::{path_example_edf_color_main_cpp}[tag=init_default_565]
include::{path_example_edf_color_main_cpp}[tag=set_rgba_565]
----

== Get Color Components

=== r(), g(), b(), a()

NOTE: `a()` only exists for `Color` not `Color565`.

[source,indent=0,c++]
----
include::{path_example_edf_color_main_cpp}[tag=init_initial_value]
include::{path_example_edf_color_main_cpp}[tag=get_rgba]

include::{path_example_edf_color_main_cpp}[tag=init_initial_value_565]
include::{path_example_edf_color_main_cpp}[tag=get_rgba_565]
----

---

=== asRGB(), asRGBA()

NOTE: `asRGBA()` only exists for `Color` not `Color565`.

[source,indent=0,c++]
----
include::{path_example_edf_color_main_cpp}[tag=init_rgba]
include::{path_example_edf_color_main_cpp}[tag=get_as]

include::{path_example_edf_color_main_cpp}[tag=init_rgba_565]
include::{path_example_edf_color_main_cpp}[tag=get_as_565]
----

== Named Colors
There are a few named colors predefined in `Color`.

.Predefined Colors
[source,indent=0,c++]
----
include::{path_src_edf_color_hpp}[tag=named_colors]
----

---

.Example Syntax to Access Predefined Colors
[source,indent=0,c++]
----
include::{path_example_edf_color_main_cpp}[tag=named_colors]
----

---

.Example of how to use Color565 and Predefined Colors
[source,indent=0,c++]
----
    include::{path_example_edf_color_main_cpp}[tag=example_565_1]
include::{path_example_edf_color_main_cpp}[tag=example_565_2]
----
