= Heap<T, N, Compare>

include::ROOT:partial$refs.adoc[]

:link_list_initialization: https://en.cppreference.com/w/cpp/language/list_initialization[list-initialization]

.Template arguments
`T` = (T)ype +
`N` = Maximum (N)umber of elements the heap can hold +
`Compare` = (Compare) functor used to specify how elements should be sorted

NOTE: `T` _Needs_ to be copyable, and _helps_ if `T` is also default constructable.

== Overview
This is a fixed max size binary heap container. Providing different `Compare` functors allows you to choose how the heap is sorted. There are two pre-defined aliases <<heap_max>> and <<heap_min>>. 

[#heap_max]
=== HeapMax<T, N>
This is an alias for a binary max heap. The examples 
[source,indent=0,c++]
----
include::{ref_src_edf_heap_hpp}[tag=declare_heap_max]
----

[#heap_min]
=== HeapMin<T, N>
This is an alias for a binary min heap. 
[source,indent=0,c++]
----
include::{ref_src_edf_heap_hpp}[tag=declare_heap_min]
----

== Initialization
Default initialization requires type `T` to be default constructable. Otherwise {link_list_initialization} is required.

.Example: `T` is default constructable
[source,indent=0,c++]
----
include::{path_example_edf_heap_main_cpp}[tag=init_max]
----

.Example: {link_list_initialization} with a custom type
[source,indent=0,c++]
----
include::{path_example_edf_heap_main_cpp}[tag=init_max_list]
----
NOTE: If using {link_list_initialization} on a type `T` without a default constructor. First fill up the entire heap using {link_list_initialization}, then call <<clear>>

== Is Questions
These member functions provide yes/no answers to the current state of the heap.

[#is_empty]
=== isEmpty()
Equivalent to `<<length>> == 0` +
Provided to make a common conditional check slightly more readable, as well as consistency with other xref:edf.adoc#_stl_like_containers[EDF containers].

.Example
[source,indent=0,c++]
----
include::{path_example_edf_heap_main_cpp}[tag=init_max]
include::{path_example_edf_heap_main_cpp}[tag=is_question_empty]
----

[#is_full]
=== isFull()
Since a heap doesn't grow the underlying container, you should check if it is full before adding an element.

.Example
[source,indent=0,c++]
----
include::{path_example_edf_heap_main_cpp}[tag=init_max]
include::{path_example_edf_heap_main_cpp}[tag=is_question_full]
----

== Capacity
Provides information about how many current elements are in the heap, as well as the max number of elements the heap can hold.

[#length]
=== length()
Returns the number of elements currently in the heap.

.Example
[source,indent=0,c++]
----
include::{path_example_edf_heap_main_cpp}[tag=init_max]
include::{path_example_edf_heap_main_cpp}[tag=capacity_length]
----

[#max_length]
=== maxLength()
Returns template parameter `N` - 1. It acts the same as a compile time constant. No need to remember how a macro for the heap max number of elements is named.

.Example
[source,indent=0,c++]
----
include::{path_example_edf_heap_main_cpp}[tag=init_max]
include::{path_example_edf_heap_main_cpp}[tag=capacity_max_length]
----

== Operations
NOTE: Many, if not all, of the Operation member functions use {ref_edf_assert_EDF_ASSERTD} to ensure the operation will be successful. Remember that the assert condition is only checked in Debug mode.

[#peek]
=== peek()
Returns the value at the root of the heap without modifying the number of elements in the heap. 

.Example
[source,indent=0,c++]
----
include::{path_example_edf_heap_main_cpp}[tag=init_max]
include::{path_example_edf_heap_main_cpp}[tag=operation_push]
include::{path_example_edf_heap_main_cpp}[tag=operation_peek]
----

[#push]
=== push( value )
Add element to the the heap. 

.Example
[source,indent=0,c++]
----
include::{path_example_edf_heap_main_cpp}[tag=init_max]
include::{path_example_edf_heap_main_cpp}[tag=operation_push]
----

[#emplace]
=== emplace( args... )
Add element to the heap by constructing the element in place using https://en.cppreference.com/w/cpp/language/new#Placement_new[placement new].

.Example
[source,indent=0,c++]
----
include::{path_example_edf_heap_main_cpp}[tag=init_max]
include::{path_example_edf_heap_main_cpp}[tag=operation_emplace]
----

[#pop]
=== pop()
Remove element from the heap then return a copy of the value.

.Example
[source,indent=0,c++]
----
include::{path_example_edf_heap_main_cpp}[tag=init_max]
include::{path_example_edf_heap_main_cpp}[tag=operation_pop]
----

[#clear]
=== clear()
Calls destructor for each element in heap. Sets the number of elements to 0.

.Example
[source,indent=0,c++]
----
include::{path_example_edf_heap_main_cpp}[tag=init_max]
include::{path_example_edf_heap_main_cpp}[tag=operation_clear]
----