= Stack<T, N>

include::ROOT:partial$refs.adoc[]

:link_list_initialization: https://en.cppreference.com/w/cpp/language/list_initialization[list-initialization]

.Template arguments
`T` = (T)ype +
`N` = Maximum (N)umber of elements the stack can hold

NOTE: `T` _Needs_ to be copyable, and _helps_ if `T` is also default constructable.

== Overview
This is a container adapter class to provide a LIFO data structure. Stack uses a {ref_edf_vector} as the underlying container. Stack has a maximum number of elements (`N`) the stack can "grow" to. 

There are 3 groups of member functions:

. <<Is Questions>>
. <<Capacity>>
. <<Operations>>

== Initialization
Default initialization requires type `T` to be default constructable. Otherwise {link_list_initialization} is required.


.Example: `T` is default constructable
[source,indent=0,c++]
----
include::{path_example_edf_stack_main_cpp}[tag=init]
----

.Example: {link_list_initialization} with a custom type
[source,indent=0,c++]
----
include::{path_example_edf_stack_main_cpp}[tag=init_no_default]
----
NOTE: If using {link_list_initialization} on a type `T` without a default constructor. First fill up the entire stack using {link_list_initialization}, then call <<clear>>

== Is Questions
These member functions provide yes/no answers to the current state of the stack.

[#is_empty]
=== isEmpty()
Equivalent to `<<length>> == 0` +
Provided to make a common conditional check slightly more readable, as well as consistency with other xref:edf.adoc#_stl_like_containers[EDF containers].

.Example
[source,indent=0,c++]
----
include::{path_example_edf_stack_main_cpp}[tag=init]
include::{path_example_edf_stack_main_cpp}[tag=is_question_empty]
----

[#is_full]
=== isFull()
Since a stack doesn't grow the underlying container, you should check if it is full before adding an element.

.Example
[source,indent=0,c++]
----
include::{path_example_edf_stack_main_cpp}[tag=init]
include::{path_example_edf_stack_main_cpp}[tag=is_question_full]
----

== Capacity
Provides information about how many current elements are in the stack, as well as the max number of elements the stack can hold.

[#length]
=== length()
Returns the number of elements currently in the stack.

.Example
[source,indent=0,c++]
----
include::{path_example_edf_stack_main_cpp}[tag=init]
include::{path_example_edf_stack_main_cpp}[tag=capacity_length]
----

[#max_length]
=== maxLength()
Returns template parameter `N`. It acts teh same as a compile time constant. No need to remember how a macro for the stack max number of elements is named.

.Example
[source,indent=0,c++]
----
include::{path_example_edf_stack_main_cpp}[tag=init]
include::{path_example_edf_stack_main_cpp}[tag=capacity_max_length]
----

== Operations
NOTE: Many, if not all, of the Operation member functions use {ref_edf_assert_EDF_ASSERTD} to ensure the operation will be successful. Remember that the assert condition is only checked in Debug mode.

[#peek]
=== peek()
Returns the last value inserted into the stack without modifying the number of elements in the stack. 

.Example
[source,indent=0,c++]
----
include::{path_example_edf_stack_main_cpp}[tag=init]
include::{path_example_edf_stack_main_cpp}[tag=operation_peek]
----

NOTE: Name is peek instead of "top" for consistency with Queue. It gives a better picture of what it does. Peek allows you to peek, look, read, the element you are likely to remove next using <<pop>> without actually popping the value.

[#push]
=== push( value )
Add element to the end of the stack. 

.Example
[source,indent=0,c++]
----
include::{path_example_edf_stack_main_cpp}[tag=init]
include::{path_example_edf_stack_main_cpp}[tag=operation_push]
----

[#emplace]
=== emplace( args... )
Add element to the end of the stack by constructing the element in place using https://en.cppreference.com/w/cpp/language/new#Placement_new[placement new].

.Example
[source,indent=0,c++]
----
include::{path_example_edf_stack_main_cpp}[tag=init]
include::{path_example_edf_stack_main_cpp}[tag=operation_emplace]
----

[#pop]
=== pop()
Remove element from the end of the stack then return a copy of the value.

.Example
[source,indent=0,c++]
----
include::{path_example_edf_stack_main_cpp}[tag=init]
include::{path_example_edf_stack_main_cpp}[tag=operation_pop]
----

[#clear]
=== clear()
Calls destructor for each element in stack. Sets the number of elements to 0.

.Example
[source,indent=0,c++]
----
include::{path_example_edf_stack_main_cpp}[tag=init]
include::{path_example_edf_stack_main_cpp}[tag=operation_clear]
----