= GPIO

include::ROOT:partial$refs.adoc[]

== Overview
GPIO is the interface for General Purpose Input-Output peripherals for all MCUs. Drivers, like an IO Expander for example, might also find it useful to implement this interface.

There are 2 groups of member functions:

. <<Input>>
. <<Output>>

== Initialization
Initialization is not done using this interface. Instead, the specific GPIO driver for a given MCU should be used for configuration.

NOTE: This also means that GPIO interrupt configuration and callback setup are not handled by this interface.

== Example Derived Class
This example showcases a simplified representation of a memory-mapped GPIO peripheral in a microcontroller. The GPIO (General Purpose Input/Output) interface presented here offers an illustration of its usage. However, it is important to note that this interface is primarily focused on reading and setting GPIO pin levels, without delving into the actual pin configuration, which are represented as empty stubs named `configureAsInput` and `configureAsOutput`.

In the code, a pseudo-memory-mapped GPIO peripheral is simulated through a structure named `MCU_GPIO_T`, which contains a single "register" called `DATA_REGISTER`. For the purpose of this example, an actual instance of this simulated peripheral, `MCU_GPIO_PORTA`, is created. Typically, in real microcontrollers, the address for such a peripheral would be obtained from the datasheet and hardcoded into the #define.

The `GPIO` class, derived from the `EDF::GPIO` base class, provides an abstraction for interacting with GPIO pins. It encapsulates the necessary attributes like the GPIO port and pin number. The constructor takes a pointer to the MCU_GPIO_T port and the specific pin number. The class overrides two pure virtual member functions, <<get_level>> and <<set>>, as required by EDF's GPIO interface.

The <<get_level>> function reads the state of the GPIO pin and returns it as a `Level` enumeration value, based on whether the corresponding bit in the DATA_REGISTER is set or not. The <<set>> function allows for setting the GPIO pin to a specified level, either `Level::HIGH` or `Level::LOW`, by modifying the `DATA_REGISTER` accordingly.

.Example
[source,c++,indent=0]
----
include::{path_example_peripherals_gpio_main_cpp}[tag=mock_gpio]
----

== Input

[#get_level]
=== getLevel()
This is a pure virtual function that retrieves and returns the current logic level of the GPIO pin. It allows you to determine whether the pin is in a high or low logic state.

Implementations of this function in derived classes should read the actual logic level of the GPIO pin and return the appropriate Level value.

.Example
[source,c++,indent=0]
----
include::{path_example_peripherals_gpio_main_cpp}[tag=init]
include::{path_example_peripherals_gpio_main_cpp}[tag=get_level]
----

---

[#is_low]
=== isLow()
This function queries the current logic level of the GPIO pin and returns `true` if it is in a low logic level state (0 volts), otherwise it returns `false`.

.Example
[source,c++,indent=0]
----
include::{path_example_peripherals_gpio_main_cpp}[tag=init]
include::{path_example_peripherals_gpio_main_cpp}[tag=is_low]
----

---

[#is_high]
=== isHigh()
This function queries the current logic level of the GPIO pin and returns `true` if it is in a high logic level state (Vdd), otherwise it returns `false`.

.Example
[source,c++,indent=0]
----
include::{path_example_peripherals_gpio_main_cpp}[tag=init]
include::{path_example_peripherals_gpio_main_cpp}[tag=is_high]
----

== Output

[#set]
=== set()
This is a pure virtual function that sets the logic level of the GPIO pin to the specified `level`.

Implementations of this function in derived classes should configure the GPIO pin to the specified logic level based on the `level` parameter.

.Example
[source,c++,indent=0]
----
include::{path_example_peripherals_gpio_main_cpp}[tag=init]
include::{path_example_peripherals_gpio_main_cpp}[tag=set]
----

---

[#toggle]
=== toggle()
This function toggles the logic level of the GPIO pin between high and low. If the pin is currently in a high logic level state, it will be set to a low logic level, and vice versa.

This function is useful for quickly switching the state of the GPIO pin without needing to read its current state.

By default, it internally calls the set function with the opposite logic level, effectively toggling the pin. It is marked virtual so that a derived class can optionally implement a more efficient version if there is a special pin toggle method in the GPIO peripheral.

.Example
[source,c++,indent=0]
----
include::{path_example_peripherals_gpio_main_cpp}[tag=init]
include::{path_example_peripherals_gpio_main_cpp}[tag=toggle]
----

---

[#set_low]
=== setLow()
This function sets the GPIO pin to a low logic level.

It is a convenient way to explicitly set the pin to a known low state without specifying the logic level as an argument.

Internally, it calls the set function with Level::LOW as the argument.

.Example
[source,c++,indent=0]
----
include::{path_example_peripherals_gpio_main_cpp}[tag=init]
include::{path_example_peripherals_gpio_main_cpp}[tag=set_low]
----

---

[#set_high]
=== setHigh()
This function sets the GPIO pin to a high logic level.

It is a convenient way to explicitly set the pin to a known high state without specifying the logic level as an argument.

Internally, it calls the set function with Level::HIGH as the argument.

.Example
[source,c++,indent=0]
----
include::{path_example_peripherals_gpio_main_cpp}[tag=init]
include::{path_example_peripherals_gpio_main_cpp}[tag=set_high]
----
